name: Convert Word to PDF

on:
  push:
    paths:
      - '**.docx'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install LibreOffice
        run: |
          sudo apt-get update
          sudo apt-get install -y libreoffice

      - name: Convert Word to PDF
        run: |
          for file in *.docx; do
            if [ -f "$file" ]; then
              echo "Converting $file to PDF"
              soffice --headless --convert-to pdf "$file"
              if [ $? -ne 0 ]; then
                echo "Error converting $file"
                exit 1
              fi
            fi
          done
        
      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.pdf
          git diff --quiet && git diff --staged --quiet || (git commit -m "Convert Word to PDF" && git push)

      - name: Check for errors
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Error in Word to PDF conversion',
              body: 'There was an error in the Word to PDF conversion workflow. Please check the action logs for more details.'
            })
